### ISSUE TITLE
feat: unique peer selection for same content filters

### ISSUE THREAD

**Issue by vitvly** [waku-org/go-waku#1001]
### Problem
Client connection stability would improve if go-waku could guarantee that multiple subscriptions to same content filters do not end  using same libp2p peers.

### Suggested solution
In case filter subscribe requests are issued with automatic peer selection enabled, consider peers already used by subscriptions with the same content filter, and do not reuse them for new subscriptions. Meaning: try to use unique peer sets for each content filter.

### Alternatives considered
A more robust and longer-term solution is being discussed here: https://github.com/waku-org/go-waku/issues/771.

### Additional context
Some time ago, status-go used to include some primitive logic for peer selection, whereby peers recently disconnected from would be downgraded in priority, and least likely to be chosen as a peer for new filter subscribes.

### Acceptance criteria
Implementation should include tests, also probably on status-go side as well.

**Comment by chaitanyaprem** [comment]
I am wondering if rather than doing this , can we include a new option in FilterSubscribe where the caller can specify how many peer subscriptions they are interested in subscribing to. In case of status-go we can always specify 2 and hence subscription would happen with 2 peers and the same shall be returned. 

Post which status-go can just keep pinging these peers and only re-request for subscription in case a peer is disconnected.

@richard-ramos @vitvly What do you guys think about this approach?

**Comment by chaitanyaprem** [comment]
> I am wondering if rather than doing this , can we include a new option in FilterSubscribe where the caller can specify how many peer subscriptions they are interested in subscribing to. In case of status-go we can always specify 2 and hence subscription would happen with 2 peers and the same shall be returned.
> 
> Post which status-go can just keep pinging these peers and only re-request for subscription in case a peer is disconnected.
> 
> @richard-ramos @vitvly What do you guys think about this approach?

cc @kaichaosun

**Comment by vitvly** [comment]
I like the idea. I'd suggest we clearly stipulate the logic of `FilterSubscribe(filter, numPeers)`, so that `numPeers` is treated as an upper limit on peer count for this particular content filter, in order to avoid accidentally subscribing to too many peers. And obviously it can return any count of subscriptions in `[0,numPeers]` interval.

**Comment by chaitanyaprem** [comment]
> in order to avoid accidentally subscribing to too many peers.

Did not get this concern, can you elaborate?

**Comment by vitvly** [comment]
> > in order to avoid accidentally subscribing to too many peers.
> 
> Did not get this concern, can you elaborate?

Sorry for confusion. I mean this:
  - client invokes `FilterSubscribe(contentFilter1, 2)` and receives 1 peer in return for whatever reason
  - upon subsequent health check client invokes `FilterSubscribe(contentFilter1, 2)` again - in this case, if a new distinct peer is available, it should return 1 peer, not 2.

**Comment by chaitanyaprem** [comment]
> > > in order to avoid accidentally subscribing to too many peers.
> > 
> > 
> > Did not get this concern, can you elaborate?
> 
> Sorry for confusion. I mean this:
> 
>     * client invokes `FilterSubscribe(contentFilter1, 2)` and receives 1 peer in return for whatever reason
> 
>     * upon subsequent health check client invokes `FilterSubscribe(contentFilter1, 2)` again - in this case, if a new distinct peer is available, it should return 1 peer, not 2.

For this additional state has to be maintained which might not be good at Filter protocol level in go-waku. 
I am wondering if such information should be at FilterManager itself in status-go. 

Also i am wondering if we are splitting responsibility and that too not in a clean way between status-go and go-waku. 
As of now status-go has a filterManager which registers for filter subscriptions, does filter pings, maintains filter peers and active subscriptions and unsubscribes based on need. But this approach would force some part of state ( peers that are already subscribed to a specific filter) to be maintained within go-waku. 

I see 2 options: 
1. status-go keeps using go-waku as it is today but with PeerSelection and takes care of ping and maintaining healthy subscription count for each filter. This would mean invoke the subscribe API by specifying how many peers are required per filter and maintain the returned peer list. In this case go-waku cannot maintain such state and use it for subsequent subscriptions i.e if a subscribe request comes for a filter it would just look for appropriate peer and subscribe to it.
2. This approach would require changes for status-go to just specify that it needs to subscribe for Filter and specifies ping interval for subscription and only maintains subs and unsubs. Go-waku takes care of managing minMentionedSubCount per filter and also do filterPing, and in case of peer disconnection resubscribe etc. 

I would like to analyze pros/cons and then decide how to move forward. WDYT @richard-ramos

**Comment by richard-ramos** [comment]
I like approach 2, I just have doubts on whether this should be part of go-waku or should be part of a layer above. In any case, perhaps a good approach would be  to be able to specify multiple criteria at the same time, i.e. maybe something like this?
```go
// Select 2 to 5 fastest peers
theNode.FilterLightClient().Subscribe(theContentFilter,  withMinPeers(2), withMaxPeers(5),  withFastestPeer())
```
That way the devs can finetune the parameters necessary for the subscription.

**Comment by chaitanyaprem** [comment]
> I like approach 2, I just have doubts on whether this should be part of go-waku or should be part of a layer above. In any case, perhaps a good approach would be to be able to specify multiple criteria at the same time, i.e. maybe something like this?
> 
> ```go
> // Select 2 to 5 fastest peers
> theNode.FilterLightClient().Subscribe(theContentFilter,  withMinPeers(2), withMaxPeers(5),  withFastestPeer())
> ```
> 
> That way the devs can finetune the parameters necessary for the subscription.

This would definitely not be at protocol layer, in-fact a layer about filter protocol.


But i am wondering if we are increasing complexity by having both Min and Max Peers. 
Take the following scenario:
1. App mentions minPeers as 2 and max as 4. 
2. For some reason we could only subscribe to 2 peers, in this case should we unsubscribe to other 2  because we couldn't subscribe to the 3rd? 

Would it be better to have only MaxPeers specified? which means we give best effort to subscribe to maxPeers but we are still ok if we can atleast subscribe to 1 of them. The app can always issue another subscribe subsequently by specifying to exclude Peer1 (to which it already has subscription) similar to how status-go does.
 
Another argument: is there a need to have more than 2 filter Peers for a filter? The idea behind having 2 is for redundancy(in case we loose connection to 1) and also in case 1 of them misses a message.

**Comment by chaitanyaprem** [comment]
> To deduplicate the same filter service node gets subscribe by the same client twice, IMO whenever the filter service node get a request for subscription, it should check the new subscription is not coming from the same peer.

The Filter service node just appends to an existing subscription any new contentTopics that are request by same peer which i think is a good approach. I am not seeing the benefit of adding this logic in filterserviceNode, rather it is the client's responsibility to maintain subscription states as well and identify duplicate subscriptions to a peer.

**Comment by chaitanyaprem** [comment]
> For the reconnection of lost filter service nodes, for now I think status-go/appdev can maintain such check. But in the future if we have a clear solution in go-waku to maintain the healthy check and reconnection for different protocols, that would be a great buy-in for devs to choose waku over other decentralized stack. It may already exist and just i'm not aware of it :)

Agreed, we can take this up in stages. We can let it be as is in status-go for now, and once the peer management in go-waku is enhanced to address this, can be removed from status-go and rely on waku's peer-manager taht can take up this responsibility.

**Comment by chaitanyaprem** [comment]
> If filter service node do not check this, it can be easily spammed with bad clients. Such spam may not bring the service node down because of the existing IP based peer limit, but it can reduce the useful services provides by such nodes.

Valid point, but even by adding a check and returning error won't solve the issue of spam. This has to be addressed by having some sort of protection for number of invalid requests by a client. This can be added under rate-limiting i guess. 
We can add such points to https://github.com/waku-org/go-waku/issues/667 issue
