### ISSUE TITLE
feat: filter admin endpoint useful for debugging

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#1002]
### Problem
Add a new Admin endpoint` /admin/v1/filter/subscriptions` for Filter that lists active subscriptions which would help in debugging.

Refer https://github.com/waku-org/waku-rest-api/pull/4 and  https://github.com/waku-org/nwaku/pull/2314

**Comment by vidhanarya** [comment]
Hey @chaitanyaprem, I would like to contribute to this issue, is it open for development?

**Comment by chaitanyaprem** [comment]
Thanks a lot for thinking of contributing to go-waku @vidhanarya . 

But this issue is no longer in required scope and hence i will be closing it.
