### ISSUE TITLE
feat: allow query messages based on message hash from waku store

### ISSUE THREAD

**Issue by kaichaosun** [waku-org/go-waku#1010]
### Problem

The message reliability is a big milestone we are trying to achieve, a few options are discussed at [here](https://www.notion.so/Messages-Over-Waku-Relay-3ded1783ecc743a4b8d0f3fd3ccb306d) and [here](https://github.com/waku-org/go-waku/issues/921). 

To ensure a message is stored by a store service node, client should be able to query a message based on message hash from store node.

Query messages based on message hash is also required in [sync protocol research](https://github.com/waku-org/research/issues/62).

### Suggested solution

Add or extend the current time range based message query to allow only query the matched messages based on a list of message hash.

**Comment by richard-ramos** [comment]
WIP in this PR: https://github.com/waku-org/go-waku/pull/1028
