### ISSUE TITLE
feat: Support message verification using multiple public keys in same pubsubTopic

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#1022]
# Problem

As of now, in status, a public key is used to verify all messages received on a topic in order to determine if they are valid or not. 

But if a single shard/pubsubTopic has to be shared by multiple communities, we need to support registering multiple keys which would be used sequentially to verify or validate messages and consider them as valid even if one of the keys work.

# Acceptance Criteria

Have tests to verify multiple keys being used for validation.

# Notes

Need to analyze performance impact for using multiple keys.

**Comment by richard-ramos** [comment]
In #1025 i added support for multiple pubkeys in both service node and client. The same feature is required in nwaku. 
cc: @waku-org/nwaku-developers, @chair28980

**Comment by fryorcraken** [comment]
This proposal open a number of questions problems.

Who decide what are the valid keys? In the case of 1 key per shard then either the app (app key ) or the community owner (community message) can communicates to members of the shard what key to use.

When supportining multiple key, then how do we expect members of community A to accept the signing key of community B? This is why an app key for shared shards was proposed in the first place.

Would be good to clarify with Status their design intent here.

**Comment by chaitanyaprem** [comment]
> Would be good to clarify with Status their design intent here.

This was something i had noticed while thinking about sharding integration in status-go. 

But if communities are to share a shard, then using a key per community will cause issues as mentioned [here](https://github.com/waku-org/go-waku/pull/1025#discussion_r1475620292)

This is something to be considered while considering which approach of sharding is to be considered in scaling.

**Comment by fryorcraken** [comment]
If community share a shard and each community use their own pre-shared signing key, then the behaviour is **unknown**.
Node in the same shard but in different communities will descore each other and remove each other from their mesh.
This may be fine, or not, as scoring is also used for connection management.

We don't know how the UX would be impacted, nor do we know if it would impact the time it takes for a node to find other nodes in the shard, with the same validation rules (ie, same community, same pre-shared key). Knowing that hte validation rules are only known once one observe the messages sent by the other peer.

If a user is joining 2 communities on the same shard then indeed, verifying messages against both key may be needed.

Having the same pre-shared key for all nodes in the same shard is a less risky bet.

This key could be an app key (or could be deterministically derived from an app key). That would be a good start.

This key could then later be set by the node operator, who is managing this shard and charging a (cheap) fee to host several communities in the same shard.

See https://notes.status.im/bxhV9tYeTAu-PLnkwzk-6w for a back of napkin design.

**Comment by chaitanyaprem** [comment]
> If community share a shard and each community use their own pre-shared signing key, then the behaviour is **unknown**. Node in the same shard but in different communities will descore each other and remove each other from their mesh. This may be fine, or not, as scoring is also used for connection management.
> 
> We don't know how the UX would be impacted, nor do we know if it would impact the time it takes for a node to find other nodes in the shard, with the same validation rules (ie, same community, same pre-shared key). Knowing that hte validation rules are only known once one observe the messages sent by the other peer.
> 
> If a user is joining 2 communities on the same shard then indeed, verifying messages against both key may be needed.
> 
> Having the same pre-shared key for all nodes in the same shard is a less risky bet.
> 
> This key could be an app key (or could be deterministically derived from an app key). That would be a good start.
> 
> This key could then later be set by the node operator, who is managing this shard and charging a (cheap) fee to host several communities in the same shard.
> 
> See https://notes.status.im/_Uxb1KpMTpKiZ23VhCbhpA for a back of napkin design.

Thanks a lot for detailed explanation of possibilities. Now i am clear.
We could create a network deployment options doc out of this which can be used by anyone who wants to run their own waku network.

**Comment by chaitanyaprem** [comment]
Closing this issue as this is approach doesn't make sense as discussed above. 
Alternative approaches are to be considered which are being done as part of permissionless sharding discussion conclusion.
