### ISSUE TITLE
Create TUI for wakunode

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#103]
- [ ] Enable / disable protocols
- [x] Display logs
- [ ] Display stats (connected peers, upload/download rate, messages stored, topics subscribed, etc)
- [ ] Manually add a peer
- [ ] Consider using https://github.com/charmbracelet/lipgloss or https://github.com/charmbracelet/bubbletea

**Comment by amirhouieh** [comment]
In case you want built a web ui, you can use [LSD react implementation](https://github.com/acid-info/lsd) - if any help please let me know, might be able to help.

**Comment by sushmitsarmah** [comment]
i am considering working on this... adding lipgloss

**Comment by chaitanyaprem** [comment]
Closing this issue as it is descoped for go-waku.
