### ISSUE TITLE
bug: message not fully propagated

### ISSUE THREAD

**Issue by cammellos** [waku-org/go-waku#1098]
1) On status community. 2 devices, mobile & desktop. Both connected to the same wifi, good connectivity.
2) I publish a message on a community channel at 09:10:56
```
DEBUG[05-10|09:10:56.594|github.com/status-im/status-go/protocol/common/message_sender.go:740]                                              sent public message                      messageID=0x9ef5221df6b9e128c4e808634901c02c7622168fa14c019348c229a6452737e0 hashes=[0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322]
```
3) The message (the whole envelope) is not received by the bridge, my desktop, another desktop user (Stefan), but it's received by Magnus a few seconds after. Once restarting the app (stefan), the message was fetched by store nodes.

4) In kibana, you can see that it made it to the fleet and https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-09T23:30:00.000Z',to:'2024-05-10T13:00:00.000Z'))&_a=(columns:!(),filters:!(),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322'),sort:!(!('@timestamp',desc)))

So it looks like the message hasn't been fully propagated through the network

**Comment by cammellos** [comment]
[abridged.txt](https://github.com/waku-org/go-waku/files/15273424/abridged.txt)

Added logs for my desktop machine (INFO level) during the time. 
I can see messages are being retrieved, but the hash `0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322` is not present, which seems to indicate it was never relayed the message to (unless it failed at a lower level and somehow we don't log that)

**Comment by cammellos** [comment]
> Just to confirm, did you sent the message via mobile which is light client and use lightpush protocol for publishing messages? @cammellos

relay on both

**Comment by chaitanyaprem** [comment]
Attaching logs from stefan 
[geth_bk.log](https://github.com/waku-org/go-waku/files/15274020/geth_bk.log)

**Comment by cammellos** [comment]
> > [abridged.txt](https://github.com/waku-org/go-waku/files/15273424/abridged.txt)
> > Added logs for my desktop machine (INFO level) during the time. I can see messages are being retrieved, but the hash `0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322` is not present, which seems to indicate it was never relayed the message to (unless it failed at a lower level and somehow we don't log that)
> 
> These logs start at time `10:00:41` whereas sender logs are at `09:10:56`. Not sure if these logs are for the same time duration. Or is it due to timezone difference?

time zone difference, on phone is UTC, while desktop is BST

**Comment by chaitanyaprem** [comment]
> [abridged.txt](https://github.com/waku-org/go-waku/files/15273424/abridged.txt)
> 
> Added logs for my desktop machine (INFO level) during the time. I can see messages are being retrieved, but the hash `0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322` is not present, which seems to indicate it was never relayed the message to (unless it failed at a lower level and somehow we don't log that)


I am noticing these logs  around the time message was sent from mobile. Is this normal and expected?

`1513 INFO [05-10|10:10:28.815|github.com/status-im/status-go/protocol/messenger_handlers.go:779]                   handling SyncInstallationCommunity
1514 ERROR[05-10|10:10:28.875|github.com/status-im/status-go/protocol/messenger_peersyncing.go:312]                payload is invalid
1515 ERROR[05-10|10:10:28.875|github.com/status-im/status-go/protocol/datasync/transport.go:58]                    failed to send message                   error="payload      is invalid"
1516 INFO [05-10|10:10:29.799|github.com/status-im/status-go/protocol/messenger.go:3925]                           processing message                       site=RetrieveA     ll hash=0x495c96dae8710ed319e45b96590ec78392686f9983da89607af6fa0e4c799cf1 message-id=0x64e56969b640f0fffa7e3ad33e3730fcea9c730ae00947a6d763df8246f20e9f
1517 INFO [05-10|10:10:29.799|github.com/status-im/status-go/protocol/messenger.go:3937]                           processing message                       type=SYNC_INST     ALLATION_COMMUNITY senderID=0x04beb57fcd3beeeb5befc4d3b5623bc52c0c472cd3dfe1cc4b38a395e781d399f7c7e565f26b85d6207c610ef52db14f3c76aee3b6d1e0f7361153b739fc6ecb37
1518 WARN [05-10|10:10:29.799|github.com/status-im/status-go/protocol/messenger_maps.go:65]                        contacts map: loading own identity       contactID=0x04     beb57fcd3beeeb5befc4d3b5623bc52c0c472cd3dfe1cc4b38a395e781d399f7c7e565f26b85d6207c610ef52db14f3c76aee3b6d1e0f7361153b739fc6ecb37
1519 ERROR[05-10|10:10:29.799|github.com/status-im/mvds/node/node.go:467]                                          Error processing message                 namespace=mvds      error="UNIQUE constraint failed: mvds_messages.id"
1520 INFO [05-10|10:10:29.799|github.com/status-im/status-go/protocol/messenger_handlers.go:779]                   handling SyncInstallationCommunity
1521 ERROR[05-10|10:10:30.079|github.com/status-im/status-go/protocol/messenger_peersyncing.go:312]                payload is invalid
`

**Comment by chaitanyaprem** [comment]
> time zone difference, on phone is UTC, while desktop is BST

Would be nice, if all are in UTC.

**Comment by cammellos** [comment]
yes, 

> payload is invalid

I will check, though is unrelated to the issue above, since the message made it to the network, so it was sent by mobile, but thanks for spotting it

**Comment by richard-ramos** [comment]
Interestingly enough, the message seems to have been received in all the nodes of the fleet. :thinking: 
I wonder if at that moment there was just no connection path between the fleet and the nodes that did not receive the message.

https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-09T23:30:00.000Z',to:'2024-05-10T13:00:00.000Z'))&_a=(columns:!(logsource,kv_raw,message),filters:!(),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322%20and%20received'),sort:!(!('@timestamp',desc)))

**Comment by chaitanyaprem** [comment]
> Interestingly enough, the message seems to have been received in all the nodes of the fleet. 🤔 I wonder if at that moment there was just no connection path between the fleet and the nodes that did not receive the message.
> 
> https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-09T23:30:00.000Z',to:'2024-05-10T13:00:00.000Z'))&_a=(columns:!(logsource,kv_raw,message),filters:!(),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'0x0d378ac7c2c8d47437e4daebfcaea501d1a5717b16521f208ad5f5f504f06322%20and%20received'),sort:!(!('@timestamp',desc)))

@cammellos mentioned that he was able to send and receive other messages during that time in his desktop. But it is odd that message being received by all nodes in the fleet, and not delivered to desktop.

**Comment by cammellos** [comment]
This means that the message is already present in the datasync and will be retried I believe, so it should be ok (albeit this error should not be shown to the user as not relevant in theory)

**Comment by chaitanyaprem** [comment]
> This means that the message is already present in the datasync and will be retried I believe, so it should be ok (albeit this error should not be shown to the user as not relevant in theory)

@cammellos on my side, i still see contact request state as "Pending" from @danisharora099 . I don't see these logs in my geth.log though.
I do have good peer connectivity and am receiving contact requests and acks from others.
Will this get resolved automatically or will it be stuck in this state ?

**Comment by cammellos** [comment]
> > This means that the message is already present in the datasync and will be retried I believe, so it should be ok (albeit this error should not be shown to the user as not relevant in theory)
> 
> @cammellos on my side, i still see contact request state as "Pending" from @danisharora099 . I don't see these logs in my geth.log though. I do have good peer connectivity and am receiving contact requests and acks from others. Will this get resolved automatically or will it be stuck in this state?

It depends, it looks like messages are not being sent from @danisharora099, or they are not making it through. In theory as soon as you receive any message from him, it should mark the request as accepted (if the code hasn't changed).
The best thing to do is to check logs and see the hash of the message and check whether it made it to your machine.

**Comment by chaitanyaprem** [comment]
Do we still observe this issue? I am guessing with frequent storev3 queries we should not be facing this anymore.

**Comment by chaitanyaprem** [comment]
Closing this issue for now, we can open a new one if we observe this behaviour again.
