### ISSUE TITLE
bug: store v3 local queries time out

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/go-waku#1106]
**Describe the bug**
Similar setup with https://github.com/waku-org/go-waku/issues/1087 but now the store v3 request just times out
Store v1 works fine and returns the stored message
In the logs you can see both v1 and v3 requests

### go-waku version/commit hash
`harbor.status.im/wakuorg/go-waku:latest`

**Additional context**
Logs:

[publishing_node.log](https://github.com/waku-org/go-waku/files/15400668/publishing_node.log)
[store_node.log](https://github.com/waku-org/go-waku/files/15400670/store_node.log)

**Comment by chaitanyaprem** [comment]
Storev3 serviceNode/server side is not implemented in go-waku as it is not required. 
This could be the reason why local storev3 queries don't work. 
But, not sure why they timeout..maybe we can just return error.

**Comment by chaitanyaprem** [comment]
Closing this as discussed here https://github.com/waku-org/go-waku/issues/1120

@fbarbu15 , we can skip this test for go-waku as local store node is not planned to be implemented.
