### ISSUE TITLE
feat: enable store service node for store v3

### ISSUE THREAD

**Issue by kaichaosun** [waku-org/go-waku#1120]
### Problem

Some status-go tests depends on go-waku to provide store services.
Store v2 already supports it, but store v3 only provides client side features.

**Comment by chaitanyaprem** [comment]
This is not being enabled since go-waku will be sunset eventually and is not expected to use a store node. 
Better not to spend effort on this, rather we can modify the tests to not depend on local store node rather simulate it. 

I am sure @richard-ramos agrees with me.

**Comment by richard-ramos** [comment]
Yeah, for this cases either we have to mockup the store functionality for the tests, or start an nwaku node.
