### ISSUE TITLE
feat: use gossipsub mesh size to report topic health for relay

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#1131]
### Problem
As of now we are using number of connected peers belonging to a pubsubTopic to report topicHealth for relay.
But a more accurate way that indicates topicHealth would be the number of fullMesh gossipsub peers available.

This would also be useful in reporting peer stats in NodeManagement tab in status desktop. 
Refer discussion here https://discord.com/channels/1110799176264056863/1252128832631345163

### Suggested solution
Use gossipsub meshpeers to identify topic health.
Should we use overall connected peer count as well somehow to indicate it? (TBD)

### Acceptance criteria
A list of tasks that need to be done for the issue to be considered resolved.

**Comment by richard-ramos** [comment]
I think that for nwaku nothing needs to be done as the `mesh` variable is public, but let's cc @Ivansete-status just in case
https://github.com/vacp2p/nim-libp2p/blob/master/libp2p/protocols/pubsub/gossipsub/types.nim#L168C5-L168C9

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem @fryorcraken
> 
> I created a fork of go-libp2p-pubsub in which I expose a function to obtain the list of full mesh peers for a topic: [waku-org/go-libp2p-pubsub#1](https://github.com/waku-org/go-libp2p-pubsub/pull/1) , so then from go-waku / status-go we could do something like this to obtain the peer count to check the topic health:
> 
> ```go
> meshPeers := waku.Relay().Pubsub().Router().(*GossipSubRouter).MeshPeers(someTopic)
> peerCnt := len(meshPeers)
> ```
> 
> The 'bad' thing is that having this would mean maintaining this fork, although looking at the release history in https://github.com/libp2p/go-libp2p-pubsub/releases gossipsub does not have that much activity, so maybe this does not represent such a big problem. A possible way to avoid this is trying to get this PR merged upstream, but I'm not sure it will be accepted because we're exposing the PubsubRouter and this is probably not an object meant for consumption by library users.
> 
> IMO having to maintain a gossipsub fork is not that problematic because we will be moving relay to nwaku, so it should be fine.
> 
> Lmk what you think.

Since gossipsub code doesn't have much changes , let's maintain this until status switches to nwaku for relay.
