### ISSUE TITLE
bug: don't ping all connected peers continuously

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#1147]
**Describe the bug**
We ping all the connected peers every fixed interval which helps us determine if we are connected or not. 
But with recent changes to enable relay to connect to upto 300 peers, this will increase un-necessary traffic and noise.

Instead we should ping only to few peers(maybe 5-10) every interval chosen randomly rather than all of them.

WDYT @richard-ramos

**Comment by richard-ramos** [comment]
Yeah i agree. Pinging all peers only made sense before the max connected peers change.
