### ISSUE TITLE
bug: peers missing in response after GET peers request

### ISSUE THREAD

**Issue by romanzac** [waku-org/go-waku#1162]
**Describe the bug**
During interop TestPeerStore::test_get_peers()  execution some nodes were missing in response after GET admin/v1/peers. This problem is not happening when nwaku nodes only are used. 1 to 2 nodes are missing in the response. This number varies for wait for discovery in interval 0 - 60 seconds. 

**To Reproduce**
1. Please checkout https://github.com/waku-org/waku-interop-tests/pull/56/commits/38322a45fc62445c90580aaba394a9e2da17f084
2. cd waku-interop-tests
3. python -m venv .venv
4. source .venv/bin/activate
5. pip install -r requirements.txt
6. pre-commit install
8. pytest tests/peer_connection_management/test_peer_store.py -k 'test_get_peers'

**Expected behavior**
Four nodes out of 5 present in response after GET peers request to Node1.

### go-waku version/commit hash
"Created": "2024-07-14T17:52:38.066699967Z" 

### nwaku version/commit hash
"commit": "f54ba10bc70cab7669ca78c6f452e9aa4741ba69",
"version": "v0.30.1-41-gf54ba1"

**Logs**

[node1_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_nwaku:latest.log](https://github.com/user-attachments/files/16228495/node1_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_nwaku.latest.log)
[node2_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_go-waku:latest.log](https://github.com/user-attachments/files/16228496/node2_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_go-waku.latest.log)
[node3_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_nwaku:latest.log](https://github.com/user-attachments/files/16228497/node3_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_nwaku.latest.log)
[node4_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_go-waku:latest.log](https://github.com/user-attachments/files/16228498/node4_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_go-waku.latest.log)
[node5_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_nwaku:latest.log](https://github.com/user-attachments/files/16228499/node5_2024-07-14_20-54-48__2fa5ae36-9fa1-498b-98da-dc9f56de3d83__harbor.status.im_wakuorg_nwaku.latest.log)

[test.log](https://github.com/user-attachments/files/16228504/test.log)

**Comment by chaitanyaprem** [comment]
When i ran the test as per steps mentioned above locally, it has passed without any issues. Ran 3 times just to confirm and all the times it has passed.

Do i need to change anything else before running?

**Comment by romanzac** [comment]
> When i ran the test as per steps mentioned above locally, it has passed without any issues. Ran 3 times just to confirm and all the times it has passed.
> 
> Do i need to change anything else before running?

Are you using the latest build please? I've custom built docker images from the latest master for both nwaku and gowaku for my local env and test is failing. The CI pipeline is using the workflow with the same settings and test has failed there as well:
https://github.com/waku-org/waku-interop-tests/actions/runs/9935039848/job/27440475894

```
FAILED tests/peer_connection_management/test_peer_store.py::TestPeerStore::test_get_peers - AssertionError: Some nodes missing in the peer store of Node ID 16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
assert ((0 == 0 and 2 == 4) or (0 > 0))
 +  where 2 = len(['16Uiu2HAmNYSJdaDwZzUpBBwasArdYen4HnEBEwo3hnQL8uZi5cab', '16Uiu2HAmVHbHMjpypXYnZBLcsyqPgxPZTUBsXMMYPiVSS44kurBs'])

```

**Comment by chaitanyaprem** [comment]
> > When i ran the test as per steps mentioned above locally, it has passed without any issues. Ran 3 times just to confirm and all the times it has passed.
> > Do i need to change anything else before running?
> 
> Are you using the latest build please? I've custom built docker images from the latest master for both nwaku and gowaku for my local env and test is failing. The CI pipeline is using the workflow with the same settings and test has failed there as well: https://github.com/waku-org/waku-interop-tests/actions/runs/9935039848/job/27440475894
> 
> ```
> FAILED tests/peer_connection_management/test_peer_store.py::TestPeerStore::test_get_peers - AssertionError: Some nodes missing in the peer store of Node ID 16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
> assert ((0 == 0 and 2 == 4) or (0 > 0))
>  +  where 2 = len(['16Uiu2HAmNYSJdaDwZzUpBBwasArdYen4HnEBEwo3hnQL8uZi5cab', '16Uiu2HAmVHbHMjpypXYnZBLcsyqPgxPZTUBsXMMYPiVSS44kurBs'])
> ```

I haven't done any changes other than the steps you had mentioned above. How will i know if latest build is being used? I saw that docker images used are from latest tag which i assumed is latest.
Let me know if i have to do something else to repro the issue.

**Comment by romanzac** [comment]
> > > When i ran the test as per steps mentioned above locally, it has passed without any issues. Ran 3 times just to confirm and all the times it has passed.
> > > Do i need to change anything else before running?
> > 
> > 
> > Are you using the latest build please? I've custom built docker images from the latest master for both nwaku and gowaku for my local env and test is failing. The CI pipeline is using the workflow with the same settings and test has failed there as well: https://github.com/waku-org/waku-interop-tests/actions/runs/9935039848/job/27440475894
> > ```
> > FAILED tests/peer_connection_management/test_peer_store.py::TestPeerStore::test_get_peers - AssertionError: Some nodes missing in the peer store of Node ID 16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
> > assert ((0 == 0 and 2 == 4) or (0 > 0))
> >  +  where 2 = len(['16Uiu2HAmNYSJdaDwZzUpBBwasArdYen4HnEBEwo3hnQL8uZi5cab', '16Uiu2HAmVHbHMjpypXYnZBLcsyqPgxPZTUBsXMMYPiVSS44kurBs'])
> > ```
> 
> I haven't done any changes other than the steps you had mentioned above. How will i know if latest build is being used? I saw that docker images used are from latest tag which i assumed is latest. Let me know if i have to do something else to repro the issue.

Could you please run on your(amd64?) box:
```
docker pull harbor.status.im/wakuorg/go-waku:latest
docker pull harbor.status.im/wakuorg/nwaku:latest
```
This will make sure your latest is the latest latest. And re-run the test please.

**Comment by chaitanyaprem** [comment]
> > > > When i ran the test as per steps mentioned above locally, it has passed without any issues. Ran 3 times just to confirm and all the times it has passed.
> > > > Do i need to change anything else before running?
> > > 
> > > 
> > > Are you using the latest build please? I've custom built docker images from the latest master for both nwaku and gowaku for my local env and test is failing. The CI pipeline is using the workflow with the same settings and test has failed there as well: https://github.com/waku-org/waku-interop-tests/actions/runs/9935039848/job/27440475894
> > > ```
> > > FAILED tests/peer_connection_management/test_peer_store.py::TestPeerStore::test_get_peers - AssertionError: Some nodes missing in the peer store of Node ID 16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
> > > assert ((0 == 0 and 2 == 4) or (0 > 0))
> > >  +  where 2 = len(['16Uiu2HAmNYSJdaDwZzUpBBwasArdYen4HnEBEwo3hnQL8uZi5cab', '16Uiu2HAmVHbHMjpypXYnZBLcsyqPgxPZTUBsXMMYPiVSS44kurBs'])
> > > ```
> > 
> > 
> > I haven't done any changes other than the steps you had mentioned above. How will i know if latest build is being used? I saw that docker images used are from latest tag which i assumed is latest. Let me know if i have to do something else to repro the issue.
> 
> Could you please run on your(amd64?) box:
> 
> ```
> docker pull harbor.status.im/wakuorg/go-waku:latest
> docker pull harbor.status.im/wakuorg/nwaku:latest
> ```
> 
> This will make sure your latest is the latest latest. And re-run the test please.

Thanks, now i am able to repro the issue...will take a look at what could be the cause.

**Comment by chaitanyaprem** [comment]
I see following logs in nwaku nodes. This is because in go-waku nodes clusterID 0 is considered as `default pubsubTopic` whereas in nwaku nodes it is considered as `static sharding cluster 0` .  

Discussion regarding this already happened here https://discord.com/channels/1110799176264056863/1111541424693985280/1260604770817933393

Can we run the tests with a non-zero clusterID and by specifying specific shards in both go-waku and nwaku? That should fix the issue.

` 337 INF 2024-07-15 10:15:30.620+00:00 disconnecting from peer                    topics="waku node peer_manager" tid=1 file=peer_manager.nim:395 peerId=16U*zyA1ac reason="     no shards in common: my_shards = [ 0 ] others_shards = [  ]"`

**Comment by romanzac** [comment]
It has worked for me. Thanks!
