### ISSUE TITLE
bug: go-waku logs zone-sensitive time

### ISSUE THREAD

**Issue by igor-sirotin** [waku-org/go-waku#1191]
# Problem 

Status user reported there're some logs that use local timezone, which exposes user's location. 
I fixed a few in status-go, but there're some in `go-waku` as well:

https://github.com/waku-org/go-waku/blob/19a47a1ac1f58de30cc3d987850f39633fc51711/waku/v2/peermanager/peer_connector.go#L210 https://github.com/waku-org/go-waku/blob/19a47a1ac1f58de30cc3d987850f39633fc51711/waku/v2/peermanager/peer_connector.go#L214 https://github.com/waku-org/go-waku/blob/19a47a1ac1f58de30cc3d987850f39633fc51711/waku/v2/peermanager/peer_connector.go#L231

# Solution

When logging, we should always convert time to UTC.

**Comment by igor-sirotin** [comment]
cc @richard-ramos @chaitanyaprem

**Comment by chaitanyaprem** [comment]
@igor-sirotin included a fix in #1192 . 

If we need this as part of current release, then i will create a PR for release branch cherry-picking this commit.

**Comment by igor-sirotin** [comment]
@chaitanyaprem though it's a simple fix, I don't like to harass cherry-picking that much.
And I didn't cherry-pick this fix as well: https://github.com/status-im/status-go/pull/5672
