### ISSUE TITLE
bug: Arm build debug

### ISSUE THREAD

**Issue by weizihua** [waku-org/go-waku#1243]
export GOOS=linux GOARCH=arm64
export CGO_ENABLES=0

make build

linux_syscall.c:67:13: error: call to undeclared function 'setresgid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: call to undeclared function 'setresuid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
make: *** [build] Error 1

How to support arm64 architecture compilation？

**Comment by chaitanyaprem** [comment]
looking at your output it looks like you are trying to build on mac env. 
i have a mac myself and i see that i am able to build without any issues. 

can you give more details as to which command you are trying to run? 


> export GOOS=linux GOARCH=arm64
> export CGO_ENABLES=0

are you setting these in your shell? you don't need to set these params explicitly

**Comment by chaitanyaprem** [comment]
Closing this issue as there is no response. please reopen if facing it with some more details.
