### ISSUE TITLE
bug:Store not wkroking when store node=go-waku

### ISSUE THREAD

**Issue by AYAHASSAN287** [waku-org/go-waku#1254]
**Describe the bug**
If sender node = go-waku  & filter_subscribed_node = go -waku  store request fails 

**To Reproduce**
1- Create 3 nodes node1[go=waku ,store =true , relay = true [
  node2 [nwaku , relay = true ]
 node3 [ go-waku , relay  = false ]

2- Node 2 publish message 
3- node3 makes store inquiry on messages 

**Expected behavior**
Node3 receives 1 message 

**Actual behavior**
500 Server Error: Internal Server Error for url: http://127.0.0.1:58971/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F1&contentTopics=%2Ftest%2F1%2Fwaku-filter%2Fproto&pageSize=5&ascending=true with response: b'{"messages":null,"error_message":"protocols not supported: [/vac/waku/store-query/3.0.0]"}'

**Screenshots**

**Desktop (please complete the following information):**

### go-waku version/commit hash
tests done using REST APIs

**Additional context**

**Comment by richard-ramos** [comment]
go-waku does not support storenode as a server. Only as a client.
This functionality is not planned to be implemented as go-waku is being sunset.

**Comment by chaitanyaprem** [comment]
Closing the issue as per above comment.
