### ISSUE TITLE
Missing flags

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#234]
The following flags and associated behaviors are missing:
- persist-peers: "Enable peer persistence: true|false"
- persist-messages: "Enable message persistence: true|false"
- dns-addrs: "Enable resolution of `dnsaddr`, `dns4` or `dns6` multiaddrs"
- discv5-table-ip-limit: "Maximum amount of nodes with the same IP in discv5 routing tables"
- discv5-bucket-ip-limit: "Maximum amount of nodes with the same IP in discv5 routing table buckets"
- discv5-bits-per-hop: "Kademlia's b variable, increase for less hops per lookup"

**Comment by richard-ramos** [comment]
cc: @chaitanyaprem 
We need to check the current status of nwaku vs go-waku to determine which flags are missing.

**Comment by chaitanyaprem** [comment]
> I was looking at the usage of dnsAddrs boolean flag, it is used to create resolver from nameserver to be passed to switchConfiguration but there is no switchConfiguration module in go-waku. Does that mean this flag is not needed for go-waku?

We shouldn't look at it that way. Each Waku implementation may choose to breakdown modules based on what underlying libp2p provides and how they design. If i look at helpText for this flag it just indicates to enable resolving multiaddresses that have domain name instead of IP. 
You will have to see in go-waku and go-libp2p if that is already done internally and can be controlled, if so then this configuration along with  --dns-addrs-name-server and --dns4-domain-name to be used for the same.

**Comment by chaitanyaprem** [comment]
> Apart from these DNS flags there are dnsDiscovery and dnsDiscoveryUrl, where discoveryUrl is ENR addr what is required using nameserver, in nwaku this nameserver is a list whereas in go-waku it is a string variable. Do me need to make it a list in go-waku? @richard-ramos

As per the code, a StringSlice is used to store (which is already a list), this means multiple times the same flag can be provided which would get captured into this StringSlice.
https://github.com/waku-org/go-waku/blob/e1a84aab0e4f29ef0f9cf62075f1784f89404512/cmd/waku/flags.go#L439

**Comment by chaitanyaprem** [comment]
> > DNSDiscovery.URLs
> 
> I wasn't talking about URLs , i have stated NameServer is a string variable in go-waku. https://github.com/waku-org/go-waku/blob/master/cmd/waku/flags.go#L446

Ok, in that case we can change it to StringSlice. Because  a user can configure more than 1 DNS for redundancy.

**Comment by richard-ramos** [comment]
> I was looking at the usage of dnsAddrs boolean flag, it is used to create resolver from nameserver to be passed to switchConfiguration but there is no switchConfiguration module in go-waku. Does that mean this flag is not needed for go-waku?

Yeah, not needed at all. Some flags only make sense for nwaku, and vice versa. go-libp2p resolves itself the dns addresses and last time i checked it's not an operation that we can control. 

> Apart from these DNS flags there are dnsDiscovery and dnsDiscoveryUrl, where discoveryUrl is ENR addr what is required using nameserver, in nwaku this nameserver is a list whereas in go-waku it is a string variable. Do me need to make it a list in go-waku? @richard-ramos

Sure! it would be nice to accept a list of nameservers, so if resolving a dns fails with one of those, we still have other options! :)

**Comment by chair28980** [comment]
Closing per discussion in go-waku pm call 2023-11-28.
