### ISSUE TITLE
feat: HTTP REST API: Store and Private APIs

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#264]
**Planned start date**:
**Due date**:

# Summary

This issue tracks the effort to add basic Store and Private HTTP REST API functionality.
Refer to nwaku API's as these have to be kept in line with them(which will eventually be part of RPC rfc)

# Acceptance Criteria

- An HTTP REST API for Waku v2 translated directly from the existing JSON-RPC REST API.
  + [x] Store REST API
  + [ ] Private REST API
  + [x] RLN support of Relay Rest API

Analyze nwaku REST API to identify what else is missing in go-waku.

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by chaitanyaprem** [comment]
@richard-ramos , Should this be made a milestone issue if all REST APi's have to be implemented?
If not, would be good to define the scope for this.

**Comment by richard-ramos** [comment]
yes, we need to turn this into a milestone, with practically the same description as https://github.com/waku-org/nwaku/issues/1076 . The only change I'd introduce is to not focus on FilterV1, as that version is already deprecated and we should probably remove support for it soon:tm:, once support for V2 is introduced in the rust bindings, and TheGraph migrates succesfully to use that version.

**Comment by chaitanyaprem** [comment]
> yes, we need to turn this into a milestone, with practically the same description as [waku-org/nwaku#1076](https://github.com/waku-org/nwaku/issues/1076) . The only change I'd introduce is to not focus on FilterV1, as that version is already deprecated and we should probably remove support for it soon™️, once support for V2 is introduced in the rust bindings, and TheGraph migrates succesfully to use that version.

Got it, Updated description. Do review and add anything else required. 
Do we have an issue to track the deprecation and changes to rust bindings? Otherwise lets create one.

**Comment by chair28980** [comment]
Closing per discussion during go-waku pm call 2023-11-21.

**Comment by chaitanyaprem** [comment]
The other REST API's are implemented and Private API is no longer available/required.
