### ISSUE TITLE
Improve and keep maintainability score of `A`

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#314]
**Planned start date**:
**Due date**:

# Summary

Code climate's [analysis of go-waku codebase](https://codeclimate.com/github/waku-org/go-waku) is as follows:
- Score maintainability: `B`

Code maintainability is one of the two fair metrics to ensure the overall quality and stability of the software.

# Acceptance Criteria

- [x] Increase Score maintainability to `A`
- [ ] Setup CI checks to maintain this metrics

## Tasks

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by fryorcraken** [comment]
How did you measure?

**Comment by fryorcraken** [comment]
@chaitanyaprem in https://notes.status.im/waku-2023-report there was two milestones:
- Increase Maintability Score. Refer to [CodeClimate report](https://codeclimate.com/github/waku-org/go-waku)
- Improve test coverage for functional tests of all protocols. Refer to [CodeClimate report](https://codeclimate.com/github/waku-org/go-waku)

But only one issue. for now, I assume one issue to track this code quality work. Feel free to split in two if you prefer.

**Comment by chaitanyaprem** [comment]
It makes sense to split this into 2 as both of these can be worked independently. Will make the split.

**Comment by chair28980** [comment]
Closing as completed, CodeClimate shows score of A.
