### ISSUE TITLE
feature request(c-bindings): allow enrtree:// addresses to be used as bootstrap nodes

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#472]
Might require some refactoring in discv5 code tho. :thinking: 

cc: @danielSanchezQ

**Comment by danielSanchezQ** [comment]
So we can do at the same time as #471 maybe?

**Comment by richard-ramos** [comment]
Implemented in https://github.com/waku-org/go-waku/pull/884 . `dnsDiscoveryURLs` config option should be used to setup all the dns discovery urls required for bootstrapping the node
