### ISSUE TITLE
test(rln-relay): rln-relay testnet 3

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#505]
See https://github.com/waku-org/nwaku/issues/1624

Tasks:
- [x] Update go-zerokit-rln to use latest zerokit/rln
- [x] Update keystore to use same format from nwaku
- [x] Refactor group management
- [x] Update chat2 to match nwaku
- [x] Handle chain forks 
- [x] Update operator docs

**Comment by chaitanyaprem** [comment]
@richard-ramos , is there anything pending in this? 
Looks like as part of #655 , looks like we are uptodate wrt RLN.
Please review and close this accordingly.

**Comment by richard-ramos** [comment]
Closing as it is already complete!
