### ISSUE TITLE
go-waku forgets it's nickname on redeployment

### ISSUE THREAD

**Issue by harmeet-status** [waku-org/go-waku#559]
We are using go-waku with SpiffWorkflow to send notifications from the workflow engine to Status Desktop. We set the nickname of Waku node however it seems to forget this on redeployment.

This is apparent when we have a new status desktop account getting a contact request. For those people who have already accepted the contact request, it will stay as-is. This is an issue for us since new people using Spiff will not be able to identify who is sending the contact request, as it is random. We normally call the nickname API and set the name to "SpiffWorkflow".

We do have persistent storage so not sure why this is happening. Can chat to @jakubgs and also @burnettk about this more.

**Comment by cammellos** [comment]
> Shouldn't this go into `status-go`?

yes, this is a status-go issue

**Comment by jakubgs** [comment]
You know, issues can be transferred between repos:

![image](https://github.com/waku-org/go-waku/assets/2212681/c3060c2d-ab19-454c-bafb-1fb6e2cf75b4)

But I see you created a new one so I'm closing this:

* https://github.com/status-im/status-go/issues/3541
