### ISSUE TITLE
Batch resume queries and filter out peers.

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#598]
The following improvements were suggested by @chaitanyaprem in https://github.com/waku-org/go-waku/pull/595

> Is there a limit on number of relay topics a node can subscribe to?
If a node subscribes to a lot of topics, in some cases running all resume in parallel would generate a burst of traffic.
Optimization: Maybe we should batch the store resume based on how far behind a node is(e.g lets say the node is offline for more than a few hours)

> Optimization: Shouldn't we filter out peerIDs that may actually have data pertaining to a topic? Probably tie this to data identified from its ENR.
Maybe the config itself for resumeNodes should be topic based, [{topic, peerList },...]

**Comment by chair28980** [comment]
No longer necessary as resume functionality no longer present.
