### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#620]
# Summary

Code climate's [analysis of go-waku codebase](https://codeclimate.com/github/waku-org/go-waku) is as follows:
- Test coverage is `D` 62%

Test coverage is one of the two fair metrics to ensure the overall quality and stability of the software.

# Acceptance Criteria
- [x] Improve test coverage in some components like utils and enabled coverage to detect folder that were not being included in report. 
- [x] Enable -race flag and ensure all tests are successful

## Tasks

- [x] #618
- [x] #661
- [x] #607

**Comment by chaitanyaprem** [comment]
**Weekly Update**
_achieved_: Enabled -race flag and ran all unit tests to identify data races.
_next_: Fix issues reported by the data race detector tool

**Comment by chaitanyaprem** [comment]
**Weekly Update**
- _achieved_: Fixed issues reported by the data race detector tool.
-_next_: identify areas where test coverage needs improvement.

**Comment by chaitanyaprem** [comment]
**Weekly Update**
- _achieved_: Improved test coverage in utils.

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: build examples as part of CI to capture compile errors

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: replace golint by revive, and add `make lint-full` target to run linting with much more rules enabled

**Comment by chaitanyaprem** [comment]
Marking this issue as completed as test coverage improvement is an on-going process and separate PR's or issues shall be created as and when identified.
