### ISSUE TITLE
[Epic] Maintenance

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#634]
# Summary

Maintenance items that do not directly fit under any other milestones, yet need to be done to avoid problems.
Typically:
- dependencies update (so that we do not wait to _need_ the upgrade to do it)
- bugs reported by users of go-waku
- Releasing

# RAID (Risks, Assumptions, Issues and Dependencies)

- This may become a dumping ground, let's thrive to not let this happen.

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: improved keep alive logic for identifying if machine is waking up; added vacuum feature to sqlite and postgresql; made migrations optional; refactored db and migration code, extracted code to generate node key to its own separate subcommand
- _next_: ?

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: refactored wakuv2 metrics to make each protocol responsable for registering and defining its own metrics

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: allow mixing named and static shards, logs succesful message pushes, concurrency fixes for filterv2

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: add tls/ws to address factory and log ENRs only after they have been setup

**Comment by chaitanyaprem** [comment]
**Weekly updates**
- _achieved_: fix panic observed in peer-manager, update filter protocol as per rfc.

**Comment by fryorcraken** [comment]
Maintenance work does not need to be tracked with an Epic. Ref: https://github.com/waku-org/pm/pull/91
