### ISSUE TITLE
chore: Implement RemovePeer in PeerManager

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#638]
### Background
As of now, peers can be added via peermanager but peer-removal is not implemented as this is not a feature exposed as an API. 

### Details
Users can remove peers from libp2p peer-store directly if they want. But this causes a gap due to introduction of service slots in peer-manager. A service-peer that is added by the user is assigned to the service-slot. 
So, when this peer is deleted it should ideally be removed from the service-slot and alternative peer should be allocated.

Ideal solution would be to have multiple service-slots so that a peer removal is straightforward.

### Acceptance criteria
A list of tasks that need to be done for the issue to be considered resolved.

**Comment by fryorcraken** [comment]
to be listed in https://github.com/waku-org/go-waku/issues/594 ?

**Comment by chaitanyaprem** [comment]
> to be listed in #594 ?

Nope, this requirement is something we don't have right now, an API to remove peer. When that is taken up, not sure when..we will have to implement this.
