### ISSUE TITLE
bug: Jenkins race job is running the default test

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#645]
**Describe the bug**
The JOB_BASE_NAME flag i.e used to segregate between race and tests job is not working. 
The JOB_BASE_NAME is returned as the PR number which doesn't match actual job name in jenkins. 
@jakubgs , I am not aware of how to fix this. Do you have any suggestions?
Tried to print the job name and realized that complete job name is something like `go-waku/prs/race/PR-<>
`

**To Reproduce**
Raise any PR and look at the results for check prs/race. 

**Expected behavior**
Tests with race flag are supposed to run when race job is being executed.

**Screenshots**
Refer to logs in one of the PRs for the same: https://ci.status.im/blue/organizations/jenkins/go-waku%2Fprs%2Frace/detail/PR-630/5/pipeline

**Comment by jakubgs** [comment]
Yeah, that format is weird, but there is a better way to do this. And we need a parameter to be able to check if it's been toggled:

* https://github.com/waku-org/go-waku/pull/648
