### ISSUE TITLE
Identify periods of no connectivity to resume message history

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#65]
Currently resuming message history is only done when starting a wakunode. It should be done instead when a node goes offline and goes online again.

**Comment by richard-ramos** [comment]
Probably related to production readiness, but store protocol should have a number of retries for when there's a failure connecting to a store node, or failure transmitting the data.

**Comment by staheri14** [comment]
> Currently resuming message history is only done when starting a wakunode. It should be done instead when a node goes offline and goes online again.

I expect the resume function to be called when a node goes off and on, isn't it the case? what does offline here mean?

**Comment by richard-ramos** [comment]
When running a go-waku node, currently it only calls resume() during startup [here](https://github.com/status-im/go-waku/blob/master/waku/v2/node/wakunode2.go#L295)  similar to how it is done in nim-waku [here](https://github.com/status-im/nim-waku/blob/master/waku/v2/node/wakunode2.nim#L1032-L1033). 

However I want to experiment calling resume when there's a connection change, which I can identify thanks to this [channel](https://github.com/status-im/go-waku/blob/master/waku/v2/node/connectedness.go#L79-L82) which receives a value each time a new peer connects / disconnects: if the number of connected peers is 0, I know that i'm offline, and if i have at least one peer connected with story protocol active, I'll know I'm online, and should call resume() to retrieve the history.

**Comment by staheri14** [comment]
> When running a go-waku node, currently it only calls resume() during startup [here](https://github.com/status-im/go-waku/blob/master/waku/v2/node/wakunode2.go#L295) similar to how it is done in nim-waku [here](https://github.com/status-im/nim-waku/blob/master/waku/v2/node/wakunode2.nim#L1032-L1033).
> 
> However I want to experiment calling resume when there's a connection change, which I can identify thanks to this [channel](https://github.com/status-im/go-waku/blob/master/waku/v2/node/connectedness.go#L79-L82) which receives a value each time a new peer connects / disconnects: if the number of connected peers is 0, I know that i'm offline, and if i have at least one peer connected with store protocol active, I'll know I'm online, and should call resume() to retrieve the history.

@richard-ramos 
It is a valid point, having no connection is equivalent to a restart which should be followed by a resume func call. We should do similarly in nim-waku, thanks for bringing this up!
