### ISSUE TITLE
to analyze: add new metrics

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#652]
In https://github.com/waku-org/go-waku/pull/586  @chaitanyaprem suggested the following improvements:

- [ ] Add count of peerExchange requests handled as well.
- [ ] Include a metric to show number of peers in peerstore
- [ ] Disclose in and out connected peer count separately (going as a label to the connectedPeerCount?)
- [ ] Consider maintaining discoveredNode metrics via separate counter per protocol or have a single one which gets updated with label as protocolName. 
- [ ] Duplicated proof (see https://github.com/waku-org/go-waku/pull/715#discussion_r1318104085)

cc: @jm-clius @alrevuelta as these metrics might make sense to be added in nwaku as well (they might even exist already, but i have not checked)

**Comment by chaitanyaprem** [comment]
Closing the issue as it is descoped for go-waku.
