### ISSUE TITLE
bug: Fix flaky connectedness test

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#657]
**Describe the bug**
The test `TestConnectionStatusChanges` under waku/v2/node is flaky and randomly keeps failing. 

2023-08-21T10:46:24.975+0530	INFO	gowaku.node2.connection-notifier	node/connectedness.go:70	peer connected	{"peer": "16Uiu2HAmS3gToFFpevWgFLi2inLFAn1kD8YVH2xHJbHKdsacDw2Z", "direction": "Inbound"}
--- FAIL: TestConnectionStatusChanges (0.04s)
    connectedness_test.go:34: 
        	Error Trace:	/Users/prem/Code/go-waku/waku/v2/node/connectedness_test.go:34
        	            				/usr/local/go/src/runtime/asm_arm64.s:1172
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestConnectionStatusChanges

**To Reproduce**
Run `make test` a few times and we can notice that the TestConnectionStatusChanges test keeps failing randomly.

**Expected behavior**
No flaky tests as it gives a bad devEx.

**Screenshots**

### go-waku version/commit hash
gowaku version 0.7.0-8a9c4d6

**Comment by richard-ramos** [comment]
Closing as this issue rarely appears on CI, and it does not affect functionality.
