### ISSUE TITLE
feat: Autosharding API for req-resp protocols

### ISSUE THREAD

**Issue by chair28980** [waku-org/go-waku#673]
This tracks the work necessary in each client to provide API(s) to applications using req-resp protocols (store, lightpush, filter, etc.) with optional pubsub topic arguments. Each client should then use autosharding to determine the associated shards on behalf of applications. Note that underlying protocols should not be affected and each client implementation should locally populate pubsub topic fields with the shards hashed from content topics received via the API.

Priority: Critical for launch

Tasks

- [x] #723 
- [x] #774

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: Completed Filter API and lightClient changes for autosharding

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: Updated lightpush API for autosharding
