### ISSUE TITLE
feat: Autosharding API for (relay) subscriptions

### ISSUE THREAD

**Issue by chair28980** [waku-org/go-waku#674]
Currently the only way to manipulate a relay node's pubsub topic subscriptions is through an explicit subscribe call with the pubsub topic as argument or via static configuration when setting up the node. This task tracks work to add a subscribe method to relevant Relay APIs allowing applications to provide desired content topics as (relay) subscribe arguments, while the node translates those to relay subscriptions for specific shards. This task should involve a mechanism where an application is only notified of new messages on subscribed content topics, instead of all messages on the subscribed shards.

Priority: Critical for launch

- [x] #779 
- [x] #807
- [x] #822

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_:  update relay to support new contentTopic based subscriptions, implement new autosharding relay RPC APIs
- _next_: implement new relay REST autoshard API

**Comment by chaitanyaprem** [comment]
Unit tests for REST API is being tracked as part of #861
