### ISSUE TITLE
feat: Peer discovery with dynamic shards as dimension

### ISSUE THREAD

**Issue by chair28980** [waku-org/go-waku#678]
Tracks work necessary to ensure that nodes can filter discovered peers according to the shards the node is currently subscribed to and for the node to update its own discoverable ENR every time its subscription set changes.

Priority: Critical for launch.

**Comment by richard-ramos** [comment]
I think part of this has been implemented already for WakuRelay since https://github.com/waku-org/go-waku/pull/595 , because anytime `Relay().Subscribe` is called or a pubsub subscription is closed, the ENR is updated with the new shards.
See https://github.com/waku-org/go-waku/blob/master/waku/v2/node/localnode.go#L288-L347

**Comment by richard-ramos** [comment]
In https://github.com/waku-org/research/issues/3 the following is described:
> Task: Peer discovery with dynamic shards as dimension
> Tracks work necessary to ensure that nodes can filter discovered peers according to the shards the node is currently subscribed to and for the node to update its own discoverable ENR every time its subscription set changes.

This does not mention specific protocols, so I have the following question: should a lightnode doing a filter subscription have its ENR affected as well? 
cc: @SionoiS

**Comment by SionoiS** [comment]
@richard-ramos 

What I did in Nwaku was to update the ENR (and filter) that discv5 use which is different from the `waku_node` one but that's impl. details.

>This does not mention specific protocols, so I have the following question: should a lightnode doing a filter subscription have its ENR affected as well?

:thinking: probably not since lightnode are not discoverable anyway.

**Comment by richard-ramos** [comment]
I see, in that case I'd consider this task to be complete.

**Comment by chaitanyaprem** [comment]
Closing this as per above discussion as it is already addressed.
Any new scenarios identified would be taken up as maintenance.
