### ISSUE TITLE
feat: Peer management with shard as a dimension

### ISSUE THREAD

**Issue by chair28980** [waku-org/go-waku#679]
If we assume that peer discovery takes care of filtering peers by shard, these peers must now be managed in a way that makes sense in a dynamic auto-sharded environment. Some requirements/ideas:

- peer manager must preferably try to keep at least a target n peers for each subscribed shard (note that dynamically subscribing/unsubscribing from shards could complicate this)
- peer manager must attempt to maintain a healthy relay connectivity for each subscribed shard
- a mechanism to perform ad-hoc discovery (or another solution) to cater for when a node subscribes to a shard for which there are no tracked peers

Priority: Critical for launch

**Comment by chaitanyaprem** [comment]
Closing this issue as first two items have already been addressed via #727. It applies for both static and autosharding.
The 3rd item, i.e ad-hoc discovery is being tracked via #680.
