### ISSUE TITLE
chore: problem with codeClimate

### ISSUE THREAD

**Issue by harsh-98** [waku-org/go-waku#689]
### Background
CodeClimate is built upon different plugins like [govet, golint, gofmt, golangci-lint etc](https://docs.codeclimate.com/docs/list-of-engines). Almost all of the suggestions in codeClimate report are from golint. But [golint has been deprecated](https://github.com/golangci/golangci-lint/issues/1892) in preference to staticcheck. 

Codeclimate has a [tool](https://github.com/codeclimate/codeclimate) available for getting these suggestions locally. I looked for a way to only run codeClimate on specific comments, but can't find it. 

Currently I have to run codeClimate separately for each file to get all the suggestions locally, this is a hassle. My codecliamte.yml config for replicating  codeClimate report locally is:
```
plugins:
  golint:
    enabled: true
```
and then run
```
docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze file_name/directory
```

Questions:
- Does someone know how to disable some golint checks in .codeclimate.yml? There is [golint config section](https://docs.codeclimate.com/docs/golint) on codeclimate website but that doesn't delve into this and golint is deprecated so info from there too.
- Can we change the golint plugin to something more configurable and active in codeClimate?

**Comment by chair28980** [comment]
Closing as fixed per go-waku pm meeting 2023-12-12.
