### ISSUE TITLE
feat: SDK: Reliable Message Subscription API for lightClient protocols

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#693]
# Summary

Refer to below issue from js-waku to get an idea. 

https://github.com/waku-org/js-waku/issues/1463 

This requires further analysis as for go-waku we will have to include both cases of being used as light-client, service-node and also there should be a way to enable/disable these features for lightClients(because in some cases, a layer above go-waku must already be implementing some of these functionalities e.g: status-go). 

Apart from the above, a way to enforce limits based on IP and message rate should also be implemented from a serviceNode point of view.

To be analyzed further to detail it down.

**Comment by chaitanyaprem** [comment]
As per discussion here https://discord.com/channels/1110799176264056863/1111540684575477821/1145970002948792420 , some of the changes related to this would be part of app-sdk/chat-sdk team.
Need to revisit the scope of changes for go-waku.

**Comment by chair28980** [comment]
Per discussion during message reliability call 2024-01-02, this is a generalized ticket and not directly pertinent to the Status x Waku integration.

**Comment by chaitanyaprem** [comment]
Closing this issue as it is already being addressed via new filterManager and storev3 based reliability for status.
