### ISSUE TITLE
feat: c-bindings RLN support

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#732]
In https://github.com/waku-org/go-waku/pull/730, I had to use `gowaku_no_rln` build tag to disable RLN support for the static and dynamic library. This is due to librln.a and librln.so being separate libraries from go-waku.

The following must be done:
1. In c-bindings example, download/buils zerokit. A script similar to what's used in nwaku to download zerokit from the github release page could be used.
2. Indicate in the documentation as well as in the script that generates the dynamic library that it is necessary to link librln.so too when using libgowaku.so/.dylib/.dll
3. Indicate in the docs the usage of `gowaku_no_rln` flag to not include RLN support

**Comment by fryorcraken** [comment]
descoped
