### ISSUE TITLE
chore: use single repository for REST API .yml files

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#739]
Currently both nwaku and go-waku have each the .yml files for REST duplicated. It would make sense to have these in a separate repository instead

cc @NagyZoltanPeter

**Comment by fryorcraken** [comment]
Added epic which makes thsi works part of the "support many platforms" milestone which is due **after** gen 0

**Comment by richard-ramos** [comment]
> @NagyZoltanPeter  Only question came to my mind, that if nwaku is the reference implementation, could not we just have the yaml's there?
Do we gain anything with such a separate repo?

It would be similar in idea to https://github.com/waku-org/waku-proto , in the aspect of it being more of a spec, than something implementation specific. It would also have the advantage of having a clearer commit history, as well as being able to introduce tools like swagger or documentation specific for the REST api. It also helps avoid having to clone a ~490MB project just to only use a couple of files, which would for sure improve CI times.

**Comment by NagyZoltanPeter** [comment]
> > @NagyZoltanPeter  Only question came to my mind, that if nwaku is the reference implementation, could not we just have the yaml's there?
> > Do we gain anything with such a separate repo?
> 
> It would be similar in idea to https://github.com/waku-org/waku-proto , in the aspect of it being more of a spec, than something implementation specific. It would also have the advantage of having a clearer commit history, as well as being able to introduce tools like swagger or documentation specific for the REST api. It also helps avoid having to clone a ~490MB project just to only use a couple of files, which would for sure improve CI times.

I'm conviced by the argument fully of having more easy to work with if stored in separate repo (that can be embed as submodule if needed).
We should somehow combine with the effort of: https://github.com/waku-org/nwaku/pull/2124
There a lot valuable comments on that already, that need to be discussed in terms, some of them can have effect on code either in nwaku or go-waku or both sides. Those ones we need to separate from the api yaml changes.

**Comment by chaitanyaprem** [comment]
Closing the issue as it is descoped for go-waku.
