### ISSUE TITLE
feat: handle postgresql reconnections

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#745]
### Problem
When using postgresql as a database, it's possible that sometimes the DB is not available. We need to investigate whether the DB being unavailable will cause any kind of panic in the execution of waku, and add a reconnection mechanism that perhaps is already provided by the postgresql dependency we are using

This task probably makes sense to do along with #607

**Comment by chaitanyaprem** [comment]
Closing as go-waku is to be sunset for nwaku.
