### ISSUE TITLE
feat: filterv2 REST API

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#746]
Implement filterV2 REST API, following this openapi yml file: https://github.com/waku-org/nwaku/pull/1890/files#diff-d0d5d66c0f96582065344acd54ce7f1b65fb973ed201435ac0689020c3464dce 
The REST api is currently located at https://github.com/waku-org/go-waku/tree/master/cmd/waku/server/rest

The focus of the task should be limited to only the REST server as the RPC can be considered deprecated and will be removed eventually so it's not worth it to add FilterV2 functionality to it.

**Comment by richard-ramos** [comment]
I think this is where we need to deviate from the defined openapi.yaml file.

We need to be able to optionally define the pubsub topic. If it is not defined, we need to derive the pubsub topic from the content topics (similar to this https://github.com/waku-org/go-waku/blob/5dfbd98c74d21664caea1d6722c28d120f52c04b/waku/v2/protocol/filter/client.go#L144C3-L156), but if specified, we need to return the messages that match both the content topic and pubsub topic.

**Comment by richard-ramos** [comment]
Perhaps a separate endpoint? i.e.:  `/filter/v2/messages_by_pubsubTopic/{pubsubTopic}/{contentTopic}`:

**Comment by chaitanyaprem** [comment]
@richard-ramos is this something that is required on rust-bindings?
Else we can descope this from go-waku.

**Comment by richard-ramos** [comment]
Not required. REST server is not used in bindings.
