### ISSUE TITLE
libp2p bug: invalid p2p address returned in call to listenAddresses() when intializing libp2p host with localhost 

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#802]
**Describe the bug**
In peermanager test code, when extracting multiaddresses for host created using localhost address go-libp2p's call to fetch listen addresses via h.Network().ListenAddresses() seems to be returning an empty p2p-circuit address which has lead to write conditional code.

Refer https://github.com/waku-org/go-waku/pull/787#discussion_r1357413506   

**Expected behavior**
Call to fetch network listen addresses should return only valid addresses.

**Comment by richard-ramos** [comment]
Closing as discussed on 02/13 go-waku PM call. This issue is already handled in the code.
