### ISSUE TITLE
chore: add tests to validate peer selection options in WakuNode

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#803]
### Background
Refer https://github.com/waku-org/go-waku/pull/787#discussion_r1357411441 for background.

Since peer-selection options have been moved to peer-manager, it is not possible to verify these with unit tests within protocols. 

### Details
Add tests at wakuNode level to verify peer-selection options for protocols.

### Acceptance criteria
All protocol peer selection options should get validated.

**Comment by chair28980** [comment]
https://codeclimate.com/github/waku-org/go-waku/waku/v2/peermanager/peer_selection.go

Closing per go-waku pm call 2023-12-05. Code coverage is around 83%.
