### ISSUE TITLE
chore: improvements for circuit relay interop

### ISSUE THREAD

**Issue by danisharora099** [waku-org/go-waku#815]
### Background
Efforts to support circuit relay interop between js-waku and go-waku were done recently through #768.

While the interop now works, some improvements can be made to make the process more efficient.

### Acceptance criteria
- [ ] allow a local go-waku node to be used as a circuit relay server instead of relying on a fleet node
   - iirc the blocker is actually on go-libp2p not being able to use a node on the same IP as a circuit relay server
- [ ] discard requirement on a secure websocket connection and allow unsecure socket connections
-  [ ] allow to read a log line to know when the ENR is populated with a p2p-circuit addrs (this currently takes ~20/25 seconds and we're manually awaiting this delay)

### Notes
- ref: https://github.com/waku-org/js-waku/pull/1619 for relevant js-waku interop tests for circuit relay

**Comment by fryorcraken** [comment]
@danisharora099 is it still needed? We icebox'd on js-waku side.
