### ISSUE TITLE
to investigate: keep streams open in filterV2

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#831]
### Background
Instead of calling Close() on the stream when pushing a message to a client, keep the stream open and reuse it.
We need to review the implications of keeping the stream open vs closing it as we do now

### Details
See discussion at: https://github.com/waku-org/go-waku/pull/823#discussion_r1369186528

**Comment by chaitanyaprem** [comment]
Closing this as this will get tracked and addressed as part of #962
