### ISSUE TITLE
feat: Support getting peers by shard  via PeerExchange

### ISSUE THREAD

**Issue by harsh-98** [waku-org/go-waku#839]
### Problem
Support getting peers by shard  via PeerExchange. 

### Suggested solution
Provide an option in the client API of peerExchange to specify clusterID and shard to filter peers that are retrieved from PeerExchange server.

**Comment by chaitanyaprem** [comment]
Changing the scope of this ticket to just provide a client side API to filter retrived peers by shard. 

If there is a need in the future the PeerExchange protocol can be upgraded to include shard based peer filtering.

**Comment by chaitanyaprem** [comment]
Implemented, hence closing.
