### ISSUE TITLE
bug: update examples to use autosharding

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#846]
While working on https://github.com/waku-org/go-waku/pull/845 I noticed that the examples weren't working correctly because the subscription nor the publish specified the pubsub topic. So a mix of using autosharding and named sharding was happening.

I 'fixed' it by using the default pubsub topic, but we should update the examples to use autosharding

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: update basic_relay example to use static and autosharding
