### ISSUE TITLE
chore: database backed peerstore is deprecated

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#852]
### Background
Remove code related to persisting peers https://github.com/waku-org/go-waku/blob/master/cmd/waku/node.go#L219-L235
If/when the peerstore is modified to use a custom implementation in go-waku, we can then consider adding back peer persistance.

```
SA1019: "github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoreds" is deprecated: The database-backed peerstore will be removed from go-libp2p in the future. Use the memory peerstore (pstoremem) instead. For more details see https://github.com/libp2p/go-libp2p/issues/2329 and https://github.com/libp2p/go-libp2p/issues/2355.
```

**Comment by chair28980** [comment]
Closing per go-waku pm call 2024-01-02.
