### ISSUE TITLE
chore: add option for relay subscriptions to drop old messages once channel is full

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#871]
**Describe the bug**
The idea would be for the subscription to act as a ring buffer and drop old messages in case the number of messages exceed the cache capacity. See discussion in https://github.com/waku-org/go-waku/pull/866#discussion_r1384855224

**Comment by chaitanyaprem** [comment]
Closing the issue as it is descoped for go-waku.

If there is an issue noticed with current subscription mechanism, then this can be looked at.
