### ISSUE TITLE
feat: add ports-shift flag similar to nwaku

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#900]
### Description
Provide a flag called --ports-shift  which is similar to nwaku. 
It shifts all port values by the port-shift specified. Useful to quickly run multiple nodes locally without changing a lot of args.

### Acceptance criteria

- [ ] Run 2 go-waku nodes locally using ports-shift and no other port arguments.

**Comment by richard-ramos** [comment]
If you set the port to 0, it will automatically get a free open port

**Comment by richard-ramos** [comment]
Hm... but now that I think more about it, perhaps combining port-shift + nodekey might be useful indeed for testing a local waku network if you want to add static nodes, although ideally the local waku network should have at least a single bootstrap node for discv5, with a fixed port and node key, and the other nodes should discover the other nodes using that boostrap node :thinking:

**Comment by chaitanyaprem** [comment]
> If you set the port to 0, it will automatically get a free open port

That is a good point, did not think of this. Just assumed since we are having default values if we don't specify, we run into conflicts while running 2 nodes. Since i was running nwaku and go-waku locally to dogfood the new Waku network.

One advantage with port-shift is that ports will be fixed and would help in using local tools like postman to test quickly by switching environments. Otherwise everytime we will have to manually find out which port was allocated in order to communicate with the node. 
Also when we have a front-end, it can use this config to connect to the Waku node REST API.

**Comment by chaitanyaprem** [comment]
> Hm... but now that I think more about it, perhaps combining port-shift + nodekey might be useful indeed for testing a local waku network if you want to add static nodes, although ideally the local waku network should have at least a single bootstrap node for discv5, with a fixed port and node key, and the other nodes should discover the other nodes using that boostrap node 🤔

Agreed that in order to test a local waku network, we will need a bootstrap node to avoid lot of hard-coded configuration and ideally use discv5. 
The scenario i had was to run multiple nodes locally that use the fleet bootstrap nodes to connect to an existing network.

**Comment by chaitanyaprem** [comment]
Closing this issue as it is descoped for go-waku.
