### ISSUE TITLE
bug: `duplicate validator for topic` error when trying to re-subscribe to previously unsubscribed topic

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/go-waku#922]
**To Reproduce**
Using REST API or RPC:
1. Subscribe to a topic
2. Un-Subscribe from that topic
3. Re-Subscribe back to that topic
=> HTTP 500 with empty response on REST
=> HTTP 400 with `duplicate validator for topic` on RPC

Error can also be seen in the attached docker log 
[node1_2023-11-23_09-46-33__2aa529bb-3b7b-47f3-8454-de0f18123539__wakuorg_go-wakulatest.log](https://github.com/waku-org/go-waku/files/13447195/node1_2023-11-23_09-46-33__2aa529bb-3b7b-47f3-8454-de0f18123539__wakuorg_go-waku.latest.log)

**Expected behavior**
This should work, it works on nwaku side. Seems that some cleanup is not done correctly when unsubscribing

### go-waku version/commit hash
wakuorg/go-waku:latest

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: fix relay subscribe API issue causing failure in resubscription to a pubsubtopic
