### ISSUE TITLE
bug: `encoding/hex: odd length hex string` for filter/v2/subscriptions POST requests

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/go-waku#928]
To Reproduce
Using REST API:

1. Connect 2 nodes on filter protocol
2. Try to filter subscribe to a topic
Ex: 
```
curl -vv -X POST "http://localhost:34710/filter/v2/subscriptions" -H "accept: text/plain" -H "content-type: application/json" -d '{"requestId":"146546546","contentFilters":["/test/1/waku-filter/proto"]
, "pubsubTopic": "/waku/2/rs/19/1"}'
```

=> HTTP 400 with no response content but in the docker log I can see **encoding/hex: odd length hex string**

Error can also be seen in the attached docker log 
[node2_2023-11-27_17-52-56__0ca635b5-7362-482e-ac1f-c750cfa0cc4f__wakuorg_go-wakulatest.log](https://github.com/waku-org/go-waku/files/13477386/node2_2023-11-27_17-52-56__0ca635b5-7362-482e-ac1f-c750cfa0cc4f__wakuorg_go-waku.latest.log)

### go-waku version/commit hash
wakuorg/go-waku:latest

**Additional context**
On nwaku this works fine

**Comment by richard-ramos** [comment]
@fbarbu15, please share the request you used that triggered that error

**Comment by richard-ramos** [comment]
Hm, indeed. Seems like `latest` is not being updated automagically. 
Maybe @yakimant  @apentori can take a look? i seem to have lost access to the docker jobs of go-waku in ci.status.im

**Comment by apentori** [comment]
There is an issue with the CI job, due to the migration with harbor registry.

**Comment by apentori** [comment]
The build is fixed, `latest` images are now accessible in harbor/ https://harbor.status.im/harbor/projects/9/repositories/go-waku/artifacts-tab/artifacts/latest.
I'm going to update the test environment to use harbor registry instead of docker hub

**Comment by fbarbu15** [comment]
> The build is fixed, `latest` images are now accessible in harbor/ https://harbor.status.im/harbor/projects/9/repositories/go-waku/artifacts-tab/artifacts/latest. I'm going to update the test environment to use harbor registry instead of docker hub

Thanks @apentori 
How do I get access to this harbor registry?
And how do I update my code to use this new image? right now I use image name: "wakuorg/go-waku:latest"

**Comment by apentori** [comment]
You can pull the image with ``docker pull harbor.status.im/wakuorg/go-waku:latest``

If you use a docker compose, you can add the registry domain name `harbor.status.im` before the image name so docker will know to use the harbor registry.

**Comment by fbarbu15** [comment]
> You can pull the image with `docker pull harbor.status.im/wakuorg/go-waku:latest`
> 
> If you use a docker compose, you can add the registry domain name `harbor.status.im` before the image name so docker will know to use the harbor registry.

Thanks, works!

**Comment by fbarbu15** [comment]
@richard-ramos confirming the fix and closing this one
