### ISSUE TITLE
chore(filter v2): unsubscribe all with unrelated peer

### ISSUE THREAD

**Issue by romanzac** [waku-org/go-waku#933]
### Background
After the call of unsubscribe all with unrelated peer, no error is returned to tell developer unsubscribe had no effect. 

### Details
I wish developer (integrator) could receive error sub message under "could not unsubscribe from peer" with reason describing this peer is unrelated or unsubscribed. 

### Acceptance criteria
Error is returned to clarify the situation. Existing test "TestUnsubscribeAllUnrelatedPeer" will pass.

**Comment by chaitanyaprem** [comment]
@romanzac fixed the underlying error in referenced PR, you can modify your test before merging and then close this issue.

**Comment by romanzac** [comment]
Thanks a lot.
