### ISSUE TITLE
Approach of storing last 5 rln roots in go-waku

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#947]
While debugging today with @rymnc today wrt RLN, we have noticed that the way go-waku serializes and stores the metadata for RLN is different from that of nwaku.

go-waku stores last 5 roots along with block numbers for those roots. 
This will cause incompatibility for:

- in case rln db has to be shared between go-waku and nwaku
- DB cannot be properly inspected with rln-inspector tool written in nwaku

@richard-ramos : Thought it would be a simple fix if we don't store block-number, but noticed that we are using to handle some chain fork and other scenarios. Can you please elaborate on the same?

@rymnc We can use this issue to discuss and decide which approach to take and proceed accordingly.

**Comment by richard-ramos** [comment]
I did not translate this part of the code 1:1 from nwaku to go-waku. Handling chain forks was code that was developed independently between implementations, as there was/is no spec for it. We can probably plan to modify go-waku to match nwaku if it is required.

Btw, what is this rln-inspector tool? maybe adding support for both go-waku and nwaku is easier than getting go-waku's code for handling chain forks to match nwaku :)

**Comment by chaitanyaprem** [comment]
> I did not translate this part of the code 1:1 from nwaku to go-waku. Handling chain forks was code that was developed independently between implementations, as there was/is no spec for it. We can probably plan to modify go-waku to match nwaku if it is required.
> 
> Btw, what is this rln-inspector tool? maybe adding support for both go-waku and nwaku is easier than getting go-waku's code for handling chain forks to match nwaku :)

nwaku doesn't handle chain forks is what i understood from @rymnc. It is also not required as per him, but i think certain scenarios would be addressed better if we handle chain forks. One scenario I could think of is following:

1. Node syncs wrong fork and post which when chain recovers, it is left with an invalid root(in case there are rln events in the forked version). 
2. This invalid root will remain until rln events occur and this invalid root becomes older than 5 roots that are stored locally. Since there is no gaurantee for rln events to happen frequently, it is possible that someone may send a valid root which got missed due to chain fork. 
The above is a very corner case but it would be better to handle it.

@richard-ramos do you think there are any other scenario would cause an issue if we don't handle chain forks?

**Comment by chaitanyaprem** [comment]
> Btw, what is this rln-inspector tool?

rln-inspector is a tool present in nwaku that can inspect a locally stored rln-tree and prints the metadata that is stored in rln-db locally. Information such as lastProcessedBlock, last 5 valid roots etc.

https://github.com/waku-org/nwaku/blob/15c1f974df17bdd686704286a6a5f035a2391fb1/Makefile#L181

**Comment by rymnc** [comment]
nwaku handles chain forks while rln-relay is running, not when restarting from the rln tree db

**Comment by chaitanyaprem** [comment]
> nwaku handles chain forks while rln-relay is running, not when restarting from the rln tree db

Ah..got it.

**Comment by chaitanyaprem** [comment]
> Btw, what is this rln-inspector tool? maybe adding support for both go-waku and nwaku is easier than getting go-waku's code for handling chain forks to match nwaku :)

This just reads the rln_tree db and prints the metadata that is stored in it. Could be useful for debugging, but i am wondering if we can just expose an admin REST API that prints this data rather than depending on another tool.
WDYT @rymnc

**Comment by rymnc** [comment]
Agreed, that is a good idea! thanks @chaitanyaprem

**Comment by chaitanyaprem** [comment]
Closing this issue as this can be addressed via REST API which is tracked via https://github.com/waku-org/go-waku/issues/983
