### ISSUE TITLE
Request: contributor access

### ISSUE THREAD

**Issue by Nasfame** [waku-org/go-waku#953]
1. Request contributor access to push directly to this repo.
2. My username Nasfame

**Comment by Nasfame** [comment]
@chaitanyaprem

**Comment by richard-ramos** [comment]
Hello, @Nasfame, thank you for considering contributing to go-waku. As described in https://github.com/waku-org/go-waku#contribution, if you'd like to contribute to go-waku, please do so via pull requests. Contributor access is not given to external contributors.
