### ISSUE TITLE
bug: NewEnvelope calculates the hash based on topic, payload and meta

### ISSUE THREAD

**Issue by kaichaosun** [waku-org/go-waku#954]
**Describe the bug**

When I move filter_tests from v1 to v2 in status-go, I need to construct many messages, some messages is not matched with filter because the msg hash is the same [resource](https://github.com/status-im/status-go/blob/develop/wakuv2/common/message.go#L187).

**Expected behavior**

The hash of Envelope should include more context like timestamp.
The hash of Waku message should include more context like timestamp if makes sense.

**Comment by richard-ramos** [comment]
The hash of the envelope is calculated as defined in https://rfc.vac.dev/spec/14/#deterministic-message-hashing
> If an optional attribute, such as meta, is absent, the concatenation of attributes SHOULD exclude it. This recommendation is made to ensure that the concatenation process proceeds smoothly when certain attributes are missing and to maintain backward compatibility.
Timestamp is one of these optional attributes.

**Comment by richard-ramos** [comment]
However, for moving the tests from V1 to V2, changing the payload's content should be enough to get a different hash

**Comment by chair28980** [comment]
Closing re: go-waku pm 2023-12-12. This is expected behavior, issue should be opened against `rfc` repo.
