### ISSUE TITLE
bug: 503 instead of 400 when a filter/v2/subscriptions bad request is sent

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/go-waku#968]
**To Reproduce**
send a bad request ex without request id:
curl -vv -X POST "http://127.0.0.1:63403/filter/v2/subscriptions" -H "accept: text/plain" -H "content-type: application/json" -d '{"contentFilters":["/
test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}'

**Actual behaviour**
 503 Service Unavailable which is misleading

**Expected behavior**
400 Bad Request

### go-waku version/commit hash
harbor.status.im/wakuorg/go-waku:latest

**Additional context**
Same thing happens for other cases:

1. request with 30+ content topics
2. wrong pubsubtopic format
3. delete filter subscriprion with no content topic

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: repro and address various issues reported by interop test team
