### ISSUE TITLE
feat: Admin REST API to fetch and track RLN Sync

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#983]
### Problem
As of now RLN sync status is not available via REST API and hence we are dependent on tools like rln_db_inspector as indicated [here](https://github.com/waku-org/go-waku/issues/947#issuecomment-1851366605)
This could lead to shipping an additional tool just to parse metadata to understand state of RLN-DB.

### Suggested solution
This can be addressed by having an Admin REST API that would just parse the DB and provide persisted RLN metadata which is the following:

- LastProcessedBlock
- ChainID
- Contract Address
- Last valid n roots
The same API could provide current state of on-going sync info as well along with persisted data.

**Comment by chaitanyaprem** [comment]
cc @waku-org/nwaku-developers

**Comment by chair28980** [comment]
@chaitanyaprem is this the relevant nwaku issue for this task: https://github.com/waku-org/nwaku/issues/2270

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem is this the relevant nwaku issue for this task: [waku-org/nwaku#2270](https://github.com/waku-org/nwaku/issues/2270)

Kind of yes. the scope of this API is to show status of RLN sync at any point in time and not just during initialization.

**Comment by chaitanyaprem** [comment]
Closing the issue as it is descoped for go-waku.
