### ISSUE TITLE
bug/regression: invalid memory address or nil pointer dereference when trying to connect nodes

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/go-waku#988]
This is a regression as it didn't happen last week

**To Reproduce**
1. Start 1st node (relay + filter): `['--listen-address=0.0.0.0', '--rpc=true', '--rpc-admin=true', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=DEBUG', '--rest-relay-cache-capacity=100', '--websocket-port=50764', '--rpc-port=50762', '--rest-port=50761', '--tcp-port=50763', '--discv5-udp-port=50765', '--rpc-address=0.0.0.0', '--rest-address=0.0.0.0', '--nat=extip:172.18.163.70', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--min-relay-peers-to-publish=0', '--legacy-filter=false', '--rest-filter-cache-capacity=50', '--relay=true', '--filter=true', '--nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68']`
2. Start 2nd node and connect it via filter to the 1st: `['--listen-address=0.0.0.0', '--rpc=true', '--rpc-admin=true', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=DEBUG', '--rest-relay-cache-capacity=100', '--websocket-port=21766', '--rpc-port=21764', '--rest-port=21763', '--tcp-port=21765', '--discv5-udp-port=21767', '--rpc-address=0.0.0.0', '--rest-address=0.0.0.0', '--nat=extip:172.18.63.29', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--min-relay-peers-to-publish=1', '--legacy-filter=false', '--rest-filter-cache-capacity=50', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Ly4QNBN2ZImHfQpDDkfEFSwTr2eYqDPd6QBLp7U5QIQNJjGCunXwXlPL9oF19b6Ri-0mIdWR18hC4xHW3FkfCe234eGAYzPXuU-gmlkgnY0gmlwhKwRAAKKbXVsdGlhZGRyc5gACgSsEQACBsZM3QMACgR_AAABBsZM3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCxkuDdWRwgsZNhXdha3UyAQ', '--filternode=/ip4/172.18.163.70/tcp/50763/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']`

**Actual behavior**
```
Node crashes with :
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe3bddd]

goroutine 264 [running]:
github.com/ethereum/go-ethereum/p2p/enode.(*Node).Record(...)
	/go/pkg/mod/github.com/status-im/go-ethereum@v1.10.25-status.4/p2p/enode/node.go:143
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).AddDiscoveredPeer(0xc0003d2a00, {0x1, {{0xc00083fe60, 0x27}, {0xc0007509c0, 0x3, 0x4}}, 0xc00033e480, {0x0, 0x0, ...}}, ...)
	/app/waku/v2/peermanager/peer_manager.go:358 +0x27d
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerConnectionStrategy).consumeSubscription(0xc0004ae770, {{0x26d7830?, 0xc00025ab90?}, 0xc00063c120?})
	/app/waku/v2/peermanager/peer_connector.go:134 +0x41d
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerConnectionStrategy).Subscribe.func1()
	/app/waku/v2/peermanager/peer_connector.go:102 +0x71
created by github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerConnectionStrategy).Subscribe
	/app/waku/v2/peermanager/peer_connector.go:100 +0x1f8

```

**Expected behavior**
Should work fine

### go-waku version/commit hash
- harbor.status.im/wakuorg/go-waku:latest

[node1_2024-01-03_14-49-11__a0721aae-311d-4582-9f93-6820954fc9d8__harbor.status.im_wakuorg_go-wakulatest.log](https://github.com/waku-org/go-waku/files/13819068/node1_2024-01-03_14-49-11__a0721aae-311d-4582-9f93-6820954fc9d8__harbor.status.im_wakuorg_go-waku.latest.log)
[node2_2024-01-03_14-49-11__a0721aae-311d-4582-9f93-6820954fc9d8__harbor.status.im_wakuorg_go-wakulatest.log](https://github.com/waku-org/go-waku/files/13819069/node2_2024-01-03_14-49-11__a0721aae-311d-4582-9f93-6820954fc9d8__harbor.status.im_wakuorg_go-waku.latest.log)

**Comment by fbarbu15** [comment]
After some more testing I think this is related to filter protocol
If the node connects via Relay I don't see this error

**Comment by chaitanyaprem** [comment]
I think i have figured out the root-cause for this. 

This peer is added statically and also discovered via discv5 with an ENR, and since we are assuming a discovered peer must already have an existing record and trying to access it is causing this panic. 

Pushed a fix in #990 , will try to retest with this fix and update.

**Comment by fbarbu15** [comment]
You are correct, it seems to happen becaue I have both `--discv5-bootstrap-node` and `--filternode=` 
If I only keep one of them there is no crash but I the filter subscription fails:

1. When not using discv5 I get:
```
2024/01/04 07:57:16 "POST http://127.0.0.1:39981/filter/v2/subscriptions HTTP/1.1" from 172.17.0.1:56454 - 400 87B in 187.788µs
2024-01-04T07:57:17.244Z	[35mDEBUG[0m	gowaku.node2.peer-manager	peermanager/peer_selection.go:86	discovering peers by pubsubTopic	{"node": "16Uiu2HAmMg4skCyTpCtXvwcmkStZGRNAb3r1FfdhAzZFe9vJJoLS", "pubsubTopics": ["/waku/2/rs/0/0"]}
2024-01-04T07:57:17.244Z	[35mDEBUG[0m	gowaku.node2.peer-manager	peermanager/peer_selection.go:97	could not retrieve random peer from slot	{"node": "16Uiu2HAmMg4skCyTpCtXvwcmkStZGRNAb3r1FfdhAzZFe9vJJoLS", "error": "no suitable peers found"}
2024-01-04T07:57:17.244Z	[31mERROR[0m	gowaku.filter	rest/filter.go:180	subscription failed	{"node": "16Uiu2HAmMg4skCyTpCtXvwcmkStZGRNAb3r1FfdhAzZFe9vJJoLS", "error": "no suitable peers found"}
```
2. When not using filternode I get:
`2024-01-04T07:54:32.351Z	[35mDEBUG[0m	basichost	basic/basic_host.go:341	failed to fetch local IPv6 address	{"node": "16Uiu2HAmG9ZRfJ5gqUf5ra5pCkAWLpxxpUShwA5FketGGAwniEPd", "error": "no route found for ::"}`

**Comment by chaitanyaprem** [comment]
> 1. When not using discv5 I get:
> 
> 
> ```
> 2024/01/04 07:57:16 "POST http://127.0.0.1:39981/filter/v2/subscriptions HTTP/1.1" from 172.17.0.1:56454 - 400 87B in 187.788µs
> 2024-01-04T07:57:17.244Z	�[35mDEBUG�[0m	gowaku.node2.peer-manager	peermanager/peer_selection.go:86	discovering peers by pubsubTopic	{"node": "16Uiu2HAmMg4skCyTpCtXvwcmkStZGRNAb3r1FfdhAzZFe9vJJoLS", "pubsubTopics": ["/waku/2/rs/0/0"]}
> 2024-01-04T07:57:17.244Z	�[35mDEBUG�[0m	gowaku.node2.peer-manager	peermanager/peer_selection.go:97	could not retrieve random peer from slot	{"node": "16Uiu2HAmMg4skCyTpCtXvwcmkStZGRNAb3r1FfdhAzZFe9vJJoLS", "error": "no suitable peers found"}
> 2024-01-04T07:57:17.244Z	�[31mERROR�[0m	gowaku.filter	rest/filter.go:180	subscription failed	{"node": "16Uiu2HAmMg4skCyTpCtXvwcmkStZGRNAb3r1FfdhAzZFe9vJJoLS", "error": "no suitable peers found"}
> ```

This is happening because you are subscribing to a pubsubTopic which is not subscribed by filternode(node1) and hence no peers are found. In order to make this work, you can pass --topic="/waku/2/rs/0/0" flag to node1 and then it should work.

**Comment by chaitanyaprem** [comment]
> You are correct, it seems to happen becaue I have both `--discv5-bootstrap-node` and `--filternode=`

Ok, in that case my fix is correct and should solve this issue.

**Comment by chaitanyaprem** [comment]
> 3\. When not using filternode I get:
> 
> 
> ```
> 2024-01-04T07:54:32.351Z	�[35mDEBUG�[0m	basichost	basic/basic_host.go:341	failed to fetch local IPv6 address	{"node": "16Uiu2HAmG9ZRfJ5gqUf5ra5pCkAWLpxxpUShwA5FketGGAwniEPd", "error": "no route found for ::"}
> ```

I don't think this is related error. Is the test passing if you don't use filternode arg? Because it should be able to discover the peer via discovery. Do note like i have mentioned above the filter-peer should already be subscribed to that pubsubTopic.
