### ISSUE TITLE
bug: stop running waku node, then create a new node and start it raise a lot of warning logs

### ISSUE THREAD

**Issue by kaichaosun** [waku-org/go-waku#995]
**Describe the bug**

I'm debuging the behaviour of network offline and online. When network resumes, I call the wakuNode.stop to stop the running node, then create a new node and start it, a lot of warning logs comes out in console take full of my screen,

```
2024-01-05T11:18:16.287+0800    WARN    pubsub  go-libp2p-pubsub@v0.9.3/tag_tracer.go:157       error bumping delivery tag: no decaying tag registered for topic /waku/2/default-waku/proto
```

**To Reproduce**
1. Go to https://github.com/threeproto/wachat and use `report-warning` branch
2. Install wails `https://wails.io/docs/gettingstarted/installation`
3. Run wachat app with `wails dev`
4. Close your wifi, then open it again
5. See console log

**Expected behavior**
No such logs. 
And call wakuNode.stop is complete to clean the resource and ready to start a new one.

**Comment by chaitanyaprem** [comment]
The log looks similar to what we have seen during a unit test failure as reported in #658 . 
Are you seeing any functional issue due to this? 
Never thought this causes a functional issue, but atleast we know the specific scenario when this is occurs.

**Comment by chaitanyaprem** [comment]
> Go to https://github.com/threeproto/wachat and use `report-warning` branch

BTW, cool sample app built on go-waku. If you plan to maintain it, then you may want to mgirate it to the public waku network by using clusterID as 1 and not use default pubsubTopic.

Also, nice to know of this wails framework to build go based frontends. Will give it a try when i get time :)

**Comment by chaitanyaprem** [comment]
> Close your wifi, then open it again

Curious to know how you are detecting node went offline (that too quite quickly)?

**Comment by chaitanyaprem** [comment]
> Close your wifi, then open it again

An unrelated question: any specific reason you bringing down and restart wakuNode when network switches from offline to online?
You can leave it as is, and when network comes back online connections get established automatically. Only thing you may want to do in your app when connection state changes is to fetch missing messages using Store protocol from a store node.

**Comment by chaitanyaprem** [comment]
> When I test go-waku/chat2 and wachat, the waku node disconnect notification happens after I shutdown the network for more than 20 seconds, and I start the network again, if not restart waku node, waku node auto reconnect happens after another maybe 20 seconds.

Do you have logs for this case? I am wondering what might be causing soo much delay. One thing could be the peer connection backoff which keeps increasing if connections keep failing.
@richard-ramos is working on addressing this as part of https://github.com/waku-org/go-waku/issues/425.
Once that is addressed, this delay should go down.

**Comment by chaitanyaprem** [comment]
At first look, this seems to be like something is not cleanedup properly at pubsub level that is causing this. 
Will take a deeper look to see how this can be resolved.

**Comment by kaichaosun** [comment]
Not in priority, close it for now.
